/// Flutter icons BloodIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BloodIcon
///      fonts:
///       - asset: fonts/BloodIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BloodIcon {
  BloodIcon._();

  static const _kFontFam = 'BloodIcon';
  static const _kFontPkg = null;

  static const IconData blood_drop_1 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
